# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://try.behave.pro.s3-website-us-west-2.amazonaws.com"
twitter_username: behavepro
github_username:  hindsightsoftware

# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

authors:
  aparkinson:
    display_name: Alan Parkinson
    author_image: "/assets/images/authors/aparkinson.png"
    email: alan.parkinson@hindsightsoftware.co.uk
    twitter: alan_parkinson
    linkedin: https://uk.linkedin.com/in/agparkinson
    github: aparkinson
  cdowler:
    display_name: Charlie Dowler
    email: charlie.dowler@hindsightsoftware.co.uk
    twitter: charliedowler
    github: charliedowler

paginate:	5

permalink:     /blog/:categories/:year/:y_day/:title.html
paginate_path: /blog/page:num

# social icons and sharing options
social:
  - icon:	twitter-square
    url:	https://twitter.com/behavepro
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/hindsightsoftware
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus-square
    url:	https://www.google.com/+Hindsighttesting
    desc:	Add us on google+
    share_url: https://plus.google.com/share
    share_title: ?text=
    share_link: "&amp;url="