# Site settings
title: Behave Pro
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://try.behave.pro"
twitter_username: behavepro
github_username:  hindsightsoftware

# Build settings
markdown: redcarpet
highlighter: rouge

bdd:
  image: /assets/images/blog/bdd.png
  colour: '#406985'
agile:
  image: /assets/images/blog/agile.png
  colour: '#fff'
updates:
  image: /assets/images/blog/updates.png
  colour: '#127DC1'
engineering:
  image: /assets/images/blog/engineering.png
  colour: '#7AC7DB'
tips:
  image: /assets/images/blog/tips.jpg
  colour: '#A0E0D0'

authors:
  aparkinson:
    display_name: Alan Parkinson
    author_image: "/assets/images/authors/aparkinson.png"
    email: alan.parkinson@hindsightsoftware.co.uk
    twitter: alan_parkinson
    linkedin: https://uk.linkedin.com/in/agparkinson
    github: aparkinson
  cdowler:
    display_name: Charlie Dowler
    email: charlie.dowler@hindsightsoftware.co.uk
    twitter: charliedowler
    github: charliedowler
  gmccreadie:
    display_name: George McCreadie
    author_image: "/assets/images/authors/gmccreadie.png"
    email: george.mccreadie@hindsightsoftware.co.uk

paginate: 5

permalink:     /blog/:categories/:year/:y_day/:title.html
paginate_path: "/blog/page:num"



# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/behavepro
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/hindsightsoftware
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google plus
    url:	https://www.google.com/+Hindsighttesting
    desc:	Add us on google+
    share_url: https://plus.google.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.google.com/+Hindsighttesting
    desc:	Follow us on LinkedIn
    share_url: http://www.linkedin.com/shareArticle
    share_title: ?title=
    share_link: "&amp;url="
